name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build project
        run: poetry build

      - name: Publish to GitHub Packages
        env:
          POETRY_HTTP_BASIC_GITHUB__USERNAME: ${{ github.actor }}
          POETRY_HTTP_BASIC_GITHUB__PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry config repositories.github https://upload.pypi.org/legacy/
          poetry publish -r github --username $POETRY_HTTP_BASIC_GITHUB__USERNAME --password $POETRY_HTTP_BASIC_GITHUB__PASSWORD
